# Generated by Django 5.1.5 on 2025-05-27 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('address', models.CharField(choices=[('I', 'Region de Tarapaca'), ('II', 'Region de Antofagasta'), ('III', 'Region de Atacama'), ('IV', 'Region de Coquimbo'), ('V', 'Region de Valparaiso'), ('RM', 'Region Metropolitana de Santiago'), ('VI', 'Region del Libertador General Bernardo OHiggins'), ('VII', 'Region del Maule'), ('VIII', 'Region del Biobio'), ('IX', 'Region de La Araucania'), ('X', 'Region de Los Lagos'), ('XI', 'Region de Aysen del General Carlos Ibanez del Campo'), ('XII', 'Region de Magallanes y de la Antartica Chilena'), ('XIV', 'Region de Los Rios'), ('XV', 'Region de Arica y Parinacota'), ('XVI', 'Region de Nuble')], max_length=255, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('material_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('email_address', models.CharField(max_length=255, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('email_address', models.CharField(max_length=255, verbose_name='Correo')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.entity', verbose_name='Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.PositiveIntegerField(unique=True, verbose_name='Numero')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.client', verbose_name='Cliente')),
                ('salesRep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.salesrep', verbose_name='Rep. Ventas')),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Descuento')),
                ('profit_margin', models.PositiveIntegerField(default=35, verbose_name='GM%')),
                ('unit_price', models.PositiveIntegerField(verbose_name='Precio unitario')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product', verbose_name='Producto')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='App.quote', verbose_name='Cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_products', to='App.template')),
            ],
        ),
    ]
