# Generated by Django 5.1.5 on 2025-05-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
