# Generated by Django 5.1.6 on 2025-05-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_template_remove_productquote_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
