# Generated by Django 5.1.5 on 2025-05-27 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_product_code_alter_product_material_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='entity',
        ),
    ]
