# Generated by Django 5.1.6 on 2025-05-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_product_material_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
