# Generated by Django 5.1.5 on 2025-05-27 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_client_entity'),
        ('AuthUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthUser.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='salesRep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthUser.salesrep', verbose_name='Rep. Ventas'),
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='SalesRep',
        ),
    ]
