# Generated by Django 5.1.5 on 2025-05-29 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_quote_client_alter_quote_salesrep_and_more'),
        ('AuthUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthUser.entity', verbose_name='Cliente'),
        ),
    ]
