# Generated by Django 5.1.5 on 2025-05-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_quote_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='public_id',
            field=models.BigIntegerField(unique=True, verbose_name='Numero'),
        ),
    ]
