# Generated by Django 5.1.5 on 2025-06-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_quote_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
