# Generated by Django 5.1.5 on 2025-06-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_quote_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='approval',
            new_name='approved',
        ),
    ]
