# Generated by Django 5.1.5 on 2025-06-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_rename_approval_quote_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
