# Generated by Django 5.1.5 on 2025-06-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_quote_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='approved',
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('AP', 'Aprobada'), ('RJ', 'Rechazada'), ('WT', 'En espera')], default='WT', max_length=50, verbose_name='Estado'),
        ),
    ]
