# Generated by Django 5.1.5 on 2025-06-04 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_remove_quote_approved_quote_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='public_id',
        ),
    ]
