# Generated by Django 5.1.5 on 2025-06-06 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_remove_quote_public_id'),
        ('AuthUser', '0004_alter_client_role_alter_salesrep_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='approved_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='AuthUser.salesrep', verbose_name='Aprobador'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='salesRep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep', to='AuthUser.salesrep', verbose_name='Rep. Ventas'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('AP', 'Aprobada'), ('RJ', 'Rechazada'), ('WT', 'En espera'), ('CL', 'Cerrada')], default='WT', max_length=50, verbose_name='Estado'),
        ),
    ]
