# Generated by Django 5.1.5 on 2025-06-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_quote_approved_by_alter_quote_salesrep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('uf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dolar', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
