# Generated by Django 5.1.5 on 2025-06-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_dailyindicators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='total',
            new_name='final',
        ),
        migrations.AddField(
            model_name='quote',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('CLP', 'CLP'), ('UF', 'UF')], default='USD', max_length=50, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='quote',
            name='iva',
            field=models.PositiveIntegerField(default=0, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='quote',
            name='total_net',
            field=models.PositiveIntegerField(default=0, verbose_name='Subtotal'),
        ),
    ]
