# Generated by Django 5.1.5 on 2025-06-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_quote_final_alter_quote_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquote',
            name='subtotal',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='productquote',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Precio unitario'),
        ),
    ]
