# Generated by Django 5.1.5 on 2025-06-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_alter_productquote_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Subtotal'),
        ),
    ]
