# Generated by Django 5.1.5 on 2025-07-08 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_productquote_subtotal_and_more'),
        ('AuthUser', '0004_alter_client_role_alter_salesrep_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthUser.client', verbose_name='Cliente'),
        ),
    ]
