# Generated by Django 5.1.5 on 2025-07-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_alter_quote_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='public_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
