# Generated by Django 5.1.5 on 2025-06-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='region',
            field=models.CharField(default='RM', max_length=255, verbose_name='Region'),
        ),
    ]
