# Generated by Django 5.1.5 on 2025-06-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUser', '0002_entity_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='region',
            field=models.CharField(choices=[('I', 'Region de Tarapaca'), ('II', 'Region de Antofagasta'), ('III', 'Region de Atacama'), ('IV', 'Region de Coquimbo'), ('V', 'Region de Valparaiso'), ('RM', 'Region Metropolitana de Santiago'), ('VI', 'Region del Libertador General Bernardo OHiggins'), ('VII', 'Region del Maule'), ('VIII', 'Region del Biobio'), ('IX', 'Region de La Araucania'), ('X', 'Region de Los Lagos'), ('XI', 'Region de Aysen del General Carlos Ibanez del Campo'), ('XII', 'Region de Magallanes y de la Antartica Chilena'), ('XIV', 'Region de Los Rios'), ('XV', 'Region de Arica y Parinacota'), ('XVI', 'Region de Nuble')], default='RM', max_length=255, verbose_name='Region'),
        ),
    ]
