# Generated by Django 5.1.5 on 2025-06-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUser', '0003_alter_entity_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('MAN', 'Gerente'), ('ENG', 'Ingeniero/a'), ('REP', 'Rep. Ventas'), ('ADM', 'Administrativo'), ('BOS', 'Jefe/a de unidad'), ('SUP', 'Supervisor/a'), ('DOC', 'Doctor/a'), ('NUR', 'Enfermero/a'), ('TEN', 'Tens')], max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='role',
            field=models.CharField(choices=[('MAN', 'Gerente'), ('ENG', 'Ingeniero/a'), ('REP', 'Rep. Ventas'), ('ADM', 'Administrativo'), ('BOS', 'Jefe/a de unidad'), ('SUP', 'Supervisor/a'), ('DOC', 'Doctor/a'), ('NUR', 'Enfermero/a'), ('TEN', 'Tens')], max_length=50, verbose_name='Cargo'),
        ),
    ]
