# Generated by Django 5.1.5 on 2025-07-09 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUser', '0004_alter_client_role_alter_salesrep_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
    ]
